#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# python make_synth_table.py   --root runs_toy_best_idc2 --out synth_table.tex

import argparse, csv, math, re
from pathlib import Path
from collections import defaultdict

METHOD_ORDER = ["Linear", "kNN", "LP", "GM", "GM-flat", "GM-instance", "GM-centroid", "kNN-budget"]
METRICS = ["acc","nll","brier","ece","smooth"]

# ----------------- Filename parsing -----------------
def parse_file_tokens(path: Path, prefix: str):
    """
    Expect filenames like:
      all_calibrations_<dataset>_<cond>[...].csv
      all_smooths_<dataset>_<cond>[...].csv
      all_summaries_<dataset>_<cond>[...].csv
    Returns (dataset, imb_flag) where imb_flag is "Yes" for longtail, else "No".
    """
    name = path.stem  # no .csv
    if not name.startswith(prefix + "_"):
        return None, None
    tail = name[len(prefix)+1:]  # after "prefix_"
    parts = tail.split("_")
    if len(parts) < 2:
        return None, None
    dataset = parts[0].lower()
    cond = parts[1].lower()
    if dataset not in ("moons","circles"):
        return None, None
    imb = "Yes" if cond in ("longtail","imbal","imb","imbalance") else "No"
    return dataset, imb

# ----------------- Method normalization -----------------
def norm_method(name: str) -> str:
    return name.strip()
    n = name.strip()
    n = n.replace("LabelSpreading","LP")
    n = re.sub(r"^GM\(.*\)$","GM", n)
    n = re.sub(r"^GM-flat\(.*\)$","GM-flat", n)
    n = re.sub(r"^GM-flat.*$","GM-flat", n)
    n = re.sub(r"^kNN-budget.*$","kNN-budget", n)
    return n

# ----------------- Safe stats -----------------
def mean_std(xs):
    if not xs: return float("nan"), float("nan")
    m = sum(xs)/len(xs)
    if len(xs) == 1: return m, 0.0
    var = sum((x-m)**2 for x in xs)/(len(xs)-1)
    return m, math.sqrt(var)

def fmt(mu_sd):
    if mu_sd is None: return "--"
    mu, sd = mu_sd
    if mu is None or math.isnan(mu): return "--"
    return f"{mu:.3f} ({sd:.3f})"

# ----------------- Readers -----------------
def ingest_calibration_file(path: Path, dataset: str, imb: str, acc_nll_brier_ece):
    with path.open("r", newline="") as f:
        rd = csv.DictReader(f)
        for r in rd:
            method = norm_method(r["method"])
            key = (dataset, imb, method)
            for m in ["acc","nll","brier","ece"]:
                v = r.get(m, "")
                if v != "":
                    try: acc_nll_brier_ece[key][m].append(float(v))
                    except: pass

def ingest_smooth_file(path: Path, dataset: str, imb: str, smooth_map):
    with path.open("r", newline="") as f:
        rd = csv.DictReader(f)
        for r in rd:
            method = norm_method(r["method"])
            key = (dataset, imb, method)
            v = r.get("smooth","")
            if v != "":
                try: smooth_map[key].append(float(v))
                except: pass

# summaries optional (kept for future extensions)
def ingest_summary_file(path: Path, dataset: str, imb: str, summary_map):
    with path.open("r", newline="") as f:
        rd = csv.DictReader(f)
        for r in rd:
            method = norm_method(r["method"])
            key = (dataset, imb, method)
            for m in ["acc","t_fit","t_pred","K"]:
                v = r.get(m, "")
                if v != "":
                    try: summary_map[key][m].append(float(v))
                    except: pass

# ----------------- Table assembly -----------------
def build_rows(acc_nll_brier_ece, smooth_map):
    grouped = defaultdict(list)  # (dataset,imb) -> list[(method, vals{metric:(mu,sd)})]
    keys = set(acc_nll_brier_ece.keys()) | set(smooth_map.keys())
    for key in keys:
        dataset, imb, method = key
        if dataset not in ("moons","circles"):
            continue
        vals = {}
        for m in ["acc","nll","brier","ece"]:
            xs = acc_nll_brier_ece.get(key, {}).get(m, [])
            if xs:
                vals[m] = mean_std(xs)
        xs = smooth_map.get(key, [])
        if xs:
            vals["smooth"] = mean_std(xs)
        if any(k in vals for k in METRICS):
            grouped[(dataset, imb)].append((method, vals))
    # order methods
    for k in grouped:
        grouped[k].sort(key=lambda t: (METHOD_ORDER.index(t[0]) if t[0] in METHOD_ORDER else 999, t[0]))
    return grouped

def write_latex(grouped, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write("% Auto-generated by make_synth_table_from_dir.py\n")
        f.write("\\begin{table}[t]\n\\centering\n\\small\n")
        f.write("\\begin{tabular}{lllccccc}\n")
        f.write("\\toprule\n")
        f.write("Dataset & Imbalanced & Method & Acc & NLL & Brier & ECE & Smooth \\\\\n")
        f.write("\\midrule\n")

        def gk_order(gk):
            ds, imb = gk
            dsr = 0 if ds=="moons" else 1
            imbr = 0 if imb=="No" else 1
            return (dsr, imbr)

        for gk in sorted(grouped.keys(), key=gk_order):
            ds, imb = gk
            for method, vals in grouped[gk]:
                f.write(f"{ds} & {imb} & {method} & "
                        f"{fmt(vals.get('acc'))} & {fmt(vals.get('nll'))} & "
                        f"{fmt(vals.get('brier'))} & {fmt(vals.get('ece'))} & "
                        f"{fmt(vals.get('smooth'))} \\\\\n")

        f.write("\\bottomrule\n\\end{tabular}\n")
        f.write("\\caption{Synthetic binary datasets. Mean (std) over runs. "
                "Lower is better for NLL, Brier, ECE, Smooth; higher is better for Acc.}\n")
        f.write("\\label{tab:synthetic}\n\\end{table}\n")

# ----------------- Main -----------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="Root folder containing all_*_{dataset}_{cond}[...].csv files")
    ap.add_argument("--out", required=True, help="Output LaTeX file (e.g., synth_results.tex)")
    args = ap.parse_args()

    root = Path(args.root)

    # storage
    acc_nll_brier_ece = defaultdict(lambda: defaultdict(list))  # (ds,imb,method)-> metric -> [vals]
    smooth_map        = defaultdict(list)                       # (ds,imb,method)-> [vals]
    summary_map       = defaultdict(lambda: defaultdict(list))  # optional

    # ingest calibrations
    for p in root.glob("all_calibrations_*.csv"):
        ds, imb = parse_file_tokens(p, "all_calibrations")
        if ds is None: continue
        ingest_calibration_file(p, ds, imb, acc_nll_brier_ece)

    # ingest smooths
    for p in root.glob("all_smooths_*.csv"):
        ds, imb = parse_file_tokens(p, "all_smooths")
        if ds is None: continue
        ingest_smooth_file(p, ds, imb, smooth_map)

    # ingest summaries (optional)
    for p in root.glob("all_summaries_*.csv"):
        ds, imb = parse_file_tokens(p, "all_summaries")
        if ds is None: continue
        ingest_summary_file(p, ds, imb, summary_map)

    grouped = build_rows(acc_nll_brier_ece, smooth_map)
    write_latex(grouped, Path(args.out))
    print(f"Wrote LaTeX table → {Path(args.out).resolve()}")

if __name__ == "__main__":
    main()
